version: '3.8'

services:
        eduverse:
                build:
                        context: .
                        dockerfile: Dockerfile
                container_name: eduverse
                ports:
                        - "8080:8080"
                volumes:
                        - ./:/app