version: '2.5'
services:
        ubuntuimage:
                container_name: mycontainer
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "8081:8081"